base_url = "https://axel.etcheverry.page"
description = "Blog personnel d'Axel Etcheverry"
default_language = "fr"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false
generate_feed = true
feed_filename = "atom.xml"       # The file name of feed, "feed.xml" / "atom.xml" / "rss.xml", read docs for more info

taxonomies = [
    {name = "tags"},             # Keep this
    {name = "categories"}        # Keep this
]

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "monokai"         # The highlight theme, choose one at https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
#extra_syntaxes_and_themes = ["syntaxes"]
render_emoji = true
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"


[extra]
name = "Axel Etcheverry"
id = "euskadi31"
bio = ""
avatar = "/img/avatar.jpeg"

show_id = true                   # Whether to show your id in homepage
show_projects = false             # Whether to show projects page

#============== Icons, you can choose at https://remixicon.com/ ====
blog_icon = "ri-quill-pen-line"
projects_icon = "ri-compasses-2-line"
home_icon = "ri-user-6-line"
rss_icon = "ri-rss-line"
toc_icon = "ri-menu-2-line"

#============== Social media links =================================
links = [
    {name = "GitHub", icon = "ri-github-line", url = "https://github.com/euskadi31"},
    {name = "Twitter", icon = "ri-twitter-line", url = "https://twitter.com/euskadi31"},
    {name = "LinkedIn", icon = "ri-linkedin-box-line", url = "https://www.linkedin.com/in/euskadi31/"},
    {name = "Instagram", icon = "ri-instagram-line", url = "https://www.instagram.com/euskadi31/"},
]

#============== Feed ===============================================
feed_in_blog_section = true      # Whether to make feed file in blog section, url will be https://example.com/blog/feed.xml, read docs for more info about rss feed

#============== Some feature switches ================================
toc = true                       # Whether to show Table-Of-Contents [Can be overridden by page config]
blur_effect = true               # Whether to turn on blur effect on navigation bar
back_to_top_button = true        # Whether to show Back-To-Top button
progress_bar = true              # Whether to show reading progress bar
cc_license = false               # Whether to show Creative-Commons statement [Can be overridden by page config]
cc_license_statement = "Ce travail est sous licence [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/)."  # The Creative-Commons statement
outdate_warn = false             # Whether to show outdate warning [Can be overridden by page config]
outdate_warn_days = 120          # How many days will a post be outdated [Can be overridden by page config]
outdate_warn_text_before = "Note: Cet article a été mis à jour pour la dernière fois il y a "
outdate_warn_text_after = " jours et pourrait ne plus être à jour."

#============== Footer =============================================
footer_copyright_name = "Axel Etcheverry"
footer_copyright_year = "2023"
# footer_custom = "xxxxxxxx"
footer_credits = true            # Whether to show "Powered by Zola and Serene" in footer

#============== Comment and Web analytics config ====================
comment = "none"                 # gitalk / disqus / disqus_js
analytics = "none"               # google_analytics / cloudflare_web_analytics / umami / baidu_tongji / goatcounter


#======================= Comment =======================

[extra.gitalk]
client_id = "xxxxxxxx"
client_secret = "xxxxxxxx"
repo = "xxxxxxxx"
owner = "xxxx"
admin = ["xxxx"]
distraction_free_mode = false
per_page = 10
page_direction = "first"
proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token"

[extra.disqus]
shortname = "xxxx"

[extra.disqus_js]
shortname = "xxxx"
apikey = "xxxx"
# site_name = "xxxx"
# identifier = "xxxx"
# url = "xxxx"
# title = "xxxx"
# api = "xxxx"
# nesting = 4
# nocomment = "xxxx"
# admin = "xxxx"
# admin_label = "xxxx"


#======================= Analytics =====================

[extra.google_analytics]
id = "G-XXXXXXXX"  # or UA-XXXXXXXX

[extra.cloudflare_web_analytics]
token = "xxxxxxxx"

[extra.umami]
website_id = "xxxxx-xxxx-xxxxx"
src = "https://xxxxxxxxxxx/umami.js"

[extra.baidu_tongji]
token = "xxxxxxxx"

[extra.goatcounter]
tag = "xxxxxxxx"
